### ISSUE TITLE
Implementing chain for Endpoint

### ISSUE THREAD

**Issue by farodin91** [ruma/ruma-api#1]
Making endpoint development faster.
Idea:
```rust
impl JoinEndpoint for Join {
  fn handle(RequestObject) -> Response {
  }
}
```

Could be behind a feature.

**Comment by jplatte** [comment]
@farodin91 Is this issues still relevant? I don't understand what is propsed here.

**Comment by jimmycuadra** [comment]
It's referring to to one of the traits used in the homeserver and is unlikely to be relevant when we choose a new web framework to replace Iron.
