### ISSUE TITLE
Rename crate

### ISSUE THREAD

**Issue by aledomu** [ruma/ruma-api#14]
This crate and `ruma-api-macros` can work as the foundation for any HTTP + JSON API. I strongly suggest to rename this to something like `http-json-api` and `http-json-api-generator` to improve the discoverability.

**Comment by jimmycuadra** [comment]
That may be incidentally true, but it's not a goal of the project, so we wouldn't officially support that use case. There are other general purpose projects for generating HTTP client libraries from API schemas (e.g. Swagger/OpenAPI) that are more appropriate for that purpose. I don't know how mature Rust support is for any of them, but that's the way to go long term.
