### ISSUE TITLE
Create macro for Endpoint

### ISSUE THREAD

**Issue by farodin91** [ruma/ruma-api#2]
```rust
endpoint! {
  method => POST,
  body => BodyParams,
  query => QueryParams,
  params => PathParams,
  path => "/_matrix/client/...",
  response => Response,
}
```

**Comment by jimmycuadra** [comment]
My plan is for [ruma-api-derive](https://github.com/ruma/ruma-api-derive) to become a Macros 2.0 procedural macro that will make this all easier.

**Comment by jplatte** [comment]
This has been done for quite some time now.
