### ISSUE TITLE
Allow dynamic query parameters

### ISSUE THREAD

**Issue by Nauxuron** [ruma/ruma-api#27]
The `ruma_api` macro needs to allow dynamic query parameters. This is necessary to support the third party network API for clients and application services (ruma/ruma-client-api#44).

I propose adding something along these lines:
```
#[ruma_api(query_map)]
query_params: HashMap<String, String>
```

This would then transform a `?foo=bar&baz=quz` query string into a map with key value pairs: `foo -> bar` and `baz -> quz`.

Potential problem: What happens when both `query_map` and `query` are specified in the same request struct? Do we first consider the `query` annotated fields and put the remaining query fields in the map? Do we not allow `query` and `query_map` in the same struct?

**Comment by jplatte** [comment]
> The `ruma_api` macro needs to allow dynamic query parameters. This is necessary to support the third party network API for clients and application services ([ruma/ruma-client-api#44](https://github.com/ruma/ruma-client-api/pull/44)).

Can you point me to the part of the spec that requires this? I can't find it.

> Do we first consider the `query` annotated fields and put the remaining query fields in the map? Do we not allow `query` and `query_map` in the same struct?

Either would be fine, I'd lean towards the first option; it shouldn't be that much harder to implement.

**Comment by Nauxuron** [comment]
Because of this: matrix-org/matrix-doc#2352

**Comment by jplatte** [comment]
Okay so that one parameter named `searchFields` is clearly a spec bug (if you could send a PR to them rewriting this to the same notations as the other endpoints, that would be great).

The `fields…` notation on the other hand is simply hard to understand. However, it doesn't seem like the list of valid query parameters for `fields…` is actually dynamic: It's the same query parameters for the client-server API that these paramters are forwarded to.

**Comment by Nauxuron** [comment]
> Okay so that one parameter named `searchFields` is clearly a spec bug (if you could send a PR to them rewriting this to the same notations as the other endpoints, that would be great).

Will do.

> The `fields…` notation on the other hand is simply hard to understand. However, it doesn't seem like the list of valid query parameters for `fields…` is actually dynamic: It's the same query parameters as for the client-server API that these are forwarded to.

Do you mean the appservice API these are forwarded to?

They are dynamic in the sense that the keys are `user_fields` and `location_fields` returned by [`/_matrix/client/r0/thirdparty/protocol/{protocol}`](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-thirdparty-protocol-protocol) endpoint.
To use the example in the spec, the IRC protocol allows you to search by `nickname` and `network`, so valid query parameters for [`/_matrix/client/r0/thirdparty/location/irc`](https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-thirdparty-location-protocol) would be `?nickname=<nickname>&network=<network>`.

**Comment by jplatte** [comment]
Alright, then I misunderstood something probably. I still don't know the basics of how application services work in matrix, but it seems like you know what you're talking about.

Given that all of the endpoints that have `field…` query params don't have other query params, maybe the easier forward is to disallow mixing for now afterall. Are you interested in implementing this yourself (I could mentor you)?
