### ISSUE TITLE
Enable automatic JSON (de)serialization of error responses

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-api#37]
Some errors are well-defined by the spec. We should (de)serialize them for the user.

**Comment by jplatte** [comment]
After some brainstorming with @timokoesters over at #ruma:matrix.org I came to the conclusion that probably the best way to implement this here is to simply let `ruma_api!` users declare an appropriate error type (and add it as an associated type with the right bounds to the `Endpoint` trait).

If anybody wants to take a stab at this, I can write up more details notes on how to proceed :)

**Comment by DevinR528** [comment]
I'd be interested in taking that stab. I have a fair amount of experience with macros/proc_macros and enjoy working on them.

**Comment by jplatte** [comment]
@DevinR528 Nice! I've been thinking to have `error: <Error type>` after the response block in `ruma_api!`. It might look a bit weird but for testing the general approach will be fine.

How about adding `type Error;` to `Endpoint` + the necessary parsing and `Error` declaration to the macro first and opening a WIP PR with that, after that we can discuss how to integrate that with the generated `TryFrom` implementations. When thinking about this I just had an idea for a refactoring of ruma-api that might conflict with other changes that could be done here.

**Comment by jplatte** [comment]
The deserialization part of this is now done (#45), serialization shouldn't be very hard to add on top of that.

**Comment by jplatte** [comment]
After looking at the APIs we now provide more closely, nother has to actually be done for the serialization side of things.
