### ISSUE TITLE
Error on non-UTF8 data in path segments

### ISSUE THREAD

**Issue by jplatte** [ruma/ruma-api#43]
Currently, the path segment deserialization code uses `decode_utf8_lossy` from percent-encoding. This is not correct as the spec says all strings **must be** encoded as utf8, so non-UTF8 data should be an error.

**Comment by ldm0** [comment]
I implemented this. But I found that this this error will never emits.

**Comment by ldm0** [comment]
Take this test code as example(It has the same structure as the code procedural macro generate):
https://github.com/ruma/ruma-api/blob/e5e89b8929859a58c2c426184d8ec0b745ba9dfe/src/lib.rs#L342-L364
The `path_segment` is `Vec<&str>` so we can ensure this vector is valid UTF-8, which makes the `decode_utf8_lossy` actually never "lose".
And you can check source code of the function `http::Request::uri()`, it uses a internal structure in `http` crate called `ByteStr` which can be ensured as valid UTF-8 string after created. Which means a http request with non-UTF8 data in path segments cannot convert into `http::Request`.
