### ISSUE TITLE
Potential API redesign to better handle endpoints without certain kinds of parameters 

### ISSUE THREAD

**Issue by jimmycuadra** [ruma/ruma-api#6]
This is a follow up to previous discussions on this topic, including #5, [my question on reddit](https://www.reddit.com/r/rust/comments/5o89f6/optional_associated_types/), and discussion in #ruma:matrix.org.

Ralith had some ideas about a different API, which would look roughly like this:

``` rust
use serde_json;

pub trait Endpoint {
    type Request: Request;
    type Response: Response;

    fn info() -> Info;
}

pub struct Info {
    pub description: &'static str,
    pub name: &'static str,
    pub rate_limited: bool,
    pub requires_authentication: bool,
    pub router_path: &'static str,
    pub request_method: Method,
}

// Wrap possible serialization errors
enum Error { /* ... */ }

pub trait Request {
    fn body(&self) -> Option<serde_json::Value>;
    fn headers(&self) -> Option<HashMap<&'static str, String>>;
    fn path(&self) -> String;
    fn query(&self) -> Option<HashMap<&'static str, String>>;
    fn from_http(request: &hyper::server::Request) -> Result<Self, Error>;
}

pub trait Response {
    type Status;

    fn body(&self) -> Option<serde_json::Value>;
    fn headers(&self) -> Option<HashMap<&'static str, String>>;
    fn status(&self) -> Self::Status;
    fn from_http(request: &hyper::client::Response) -> Result<Self, Error>;
}
```

This issue is for everyone to evaluate this proposed API, considering how it would work from both the client (serializing requests and deserializing responses) and server (deserializing requests and serializing responses) sides.

/cc @Ralith @vberger @eternaleye @jplatte @exul

**Comment by jimmycuadra** [comment]
We can probably defer any major API change along these lines because I think our immediate needs will be handled by this commit I just pushed to ruma-client: https://github.com/ruma/ruma-client/commit/212d3a5e7bb34fdabd3c0d0cdec7ab2220169d06.

**Comment by vberger** [comment]
Just to be clear we're on the same page, with this interface specification, the `Request` and `Response` types would be, for each endpoint, a struct containing all the fields necessary, that the user would construct / deconstruct at will, and then the `Response` and `Request` traits would be used internally by ruma to make the translation to/from HTTP queries. Is that correct?

Under the assumption that I didn't misunderstand, this looks quite good. It moves the serialization burden to ruma-api's `Endpoint`s and their implementation, which will allow for easy handling of corner cases I believe.

Also, it nicely hides the "params are split between path query and body" madness of the matrix spec.

OTOH, we'll probably need to think about how to automate these implementations as much as possible, (with macros maybe ?), because they are gonna be very repetitive.

**Comment by jplatte** [comment]
I am somewhat unsure about the `from_http` members in `Request` and `Response`. Given that ruma requires the `try_from` feature anyway, should we maybe use that instead to keep our new traits focused on just providing info about a request / response? Also: Why is the `status(&self)` return value in `Response` an associated type?

In any case, this already looks like it will be much more pleasant to work with, even though it won't matter so much on client side when ruma-client wraps it all in a better API again.

Pinging @neosam too in case he's not already following the discussion.

**Comment by jimmycuadra** [comment]
@vberger Yes, your understanding is correct. I agree that this will add a lot more boilerplate code that will be painful to write by hand. That is one of the downsides.

@jplatte Yes, I thought about using TryFrom also. As it's currently written, having the `from_http` method also ties our API directly to Hyper, which I'd like to avoid. Using a TryFrom conversion could let us decouple that. But really, the other methods exposed are really just a conversion API also, so you could argue that we could replace the entire Request and Response traits by adding TryFrom bounds to the associated types. Something like:

``` rust
pub trait Endpoint {
    type Request: Into<hyper::client::Request> + TryFrom<hyper::server::Request>
    type Response: Into<hyper::server::Response> + TryFrom<hyper::client::Response>
}
```

That doesn't solve the problem of being tied to Hyper, but it could potentially cut down on trait implementation boilerplate, and it's more clear what the purpose of the associated types are.

Another far-future compatibility concern is whether or not this API ties us too specifically to HTTP. The Matrix devs have talked about the possibility of more efficient transports in the future, like protocol buffers or a similar system. That's probably the wrong thing to optimize for, though. As they say, delay your decisions as long as possible until you have the most possible information, and we have close to zero information about what that future system would look like. Also, with the exception of the `from_http` methods, this isn't a lot more HTTP specific than the current API.

**Comment by vberger** [comment]
On the question of being tied to hyper, or any transport generally, there is still the possibility of doing something like this:

```rust
pub trait Endpoint {
    type Request;
    type Response;
    fn info() -> Info;
}

pub trait HyperHTTPEndpoint: Endpoint
    where <Self as Endpoint>::Request: Into<hyper::client::Request> + TryFrom<hyper::server::Request>,
          <Self as Endpoint>::Response: Into<hyper::server::Response> + TryFrom<hyper::client::Response>
{
}

impl<T> HyperHTTPEndpoint for T
    where T: Endpoint,
          <T as Endpoint>::Request: Into<hyper::client::Request> + TryFrom<hyper::server::Request>,
          <T as Endpoint>::Response: Into<hyper::server::Response> + TryFrom<hyper::client::Response>
{
}
```

This leaves open the door to using other HTTP implementations / other transports, while keeping the associated cost minimal: you _still_ just need to impl `Endpoint` and the `Into`/`TryFrom` traits.

**Comment by jplatte** [comment]
I think as long as the Matrix spec splits things up into path, query and body parameters, it's unrealistic for it to work over anything but HTTP. I also doubt that trying to not tie ourselves to Hyper is going to buy us anything, so I'm somewhat in favor of the variant Jimmy proposed (assuming the only difference is the tying to Hyper, and the omission of the info function was accidental / just for brevity).

Given my expertise in macros basically being non-existant, I'd like to have a look at how we could reduce boilerplates with them here. I think it should be more-or-less straight-forward to create a macro that creates a Response type and its `Into` and `TryFrom` impls, right? Request will be more involved either way, though once we have those two Endpoint structs should be easy. I guess a whole different strategy would be to create that new kind of macro that would allow `#[derive(Response)]`? Would be harder to do for Request again, and probably require some form of additional trait or field annotation for the different parameters. Thoughts?

**Comment by jimmycuadra** [comment]
> assuming the only difference is the tying to Hyper, and the omission of the info function was accidental / just for brevity

Yeah, just cause it wasn't related to the change I was showing.

Tying the API to Hyper is not totally a theoretical concern. For example, it would mean we'd have to jump through additional hoops or break the API to switch from Hyper to Reqwest on the client side, or the next great HTTP client that comes along. Similarly on the server side, we're not even using Hyper's response type directly in ruma right now, but Iron's response type. Web frameworks are still in the early days in Rust, and it's very likely that we will not be using Iron forever. Even in the last month, Rocket has become the new hotness.

**Comment by jplatte** [comment]
Alright, that makes sense. I'm convinced.

**Comment by jimmycuadra** [comment]
Another downside of this API is that we won't have structs for the different kinds of parameters for each endpoint, so we won't be able to use Serde's functions for quick one-to-one conversions. For example, on the server side, we could no longer deserialize an HTTP request's body directly into a struct, because there would only be one struct containing all of the body, query, and path parameters.

**Comment by jimmycuadra** [comment]
Closing in favor of actual code in #9.
